CREATE TABLE TRANSACTIONS_DEVSU
(
    transactionId   BIGINT NOT NULL AUTO_INCREMENT,
    transactionDate datetime NULL,
    transactionType VARCHAR(255) NULL,
    amount           VARCHAR(255) NULL,
    balance          VARCHAR(255) NULL,
    accountId       BIGINT NOT NULL,
    personId        BIGINT NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (transactionId)
);

ALTER TABLE TRANSACTIONS_DEVSU
    ADD CONSTRAINT FK_TRANSACTIONS_ON_ACCOUNTID FOREIGN KEY (accountId) REFERENCES ACCOUNT_DEVSU (accountId);

ALTER TABLE TRANSACTIONS_DEVSU
    ADD CONSTRAINT FK_TRANSACTIONS_ON_PERSON FOREIGN KEY (personId) REFERENCES CLIENT_DEVSU (personId);